# PyPI Uploading

name: PyPI Upload

on:
  push:
    branches:
      - main

jobs:
  upload-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install twine

      - name: Login to PyPI
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine login --username $PYPI_USERNAME --password $PYPI_PASSWORD

      - name: Upload package
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          PACKAGE_NAME: 'chinese_restaurant_process'
          PACKAGE_VERSION: '1.0.0'
        run: |
          python -m twine upload dist/*
